-- AlterTable
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "isNeutralSite" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "venueName" TEXT;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "venueCity" TEXT;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "venueCountry" TEXT;
ALTER TABLE "Game" DROP COLUMN IF EXISTS "venueState";
